# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import kelola_dokter as kd
import kelola_perawat as kpr
import kelola_pasien as kps
import kelola_pemeriksaan as kpm
import kelola_admin as ka
import kelola_kasir as kk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 670)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 631))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 190, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 450, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(320, 190, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(320, 450, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 320, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(620, 320, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1131, 111))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 0, 255);\n"
"    border-radius: 5px        \n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(460, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color : white\n"
"    }")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1010, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 0, 0);\n"
"   color: white;    \n"
"   border-radius: 5px;   \n"
"   padding: 6px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton.clicked.connect(self.open_dokter)
        self.pushButton_2.clicked.connect(self.open_perawat)
        self.pushButton_3.clicked.connect(self.open_pasien)
        self.pushButton_4.clicked.connect(self.open_pemeriksaan)
        self.pushButton_6.clicked.connect(self.open_kasir)
        self.pushButton_7.clicked.connect(self.open_admin)
        self.pushButton_5.clicked.connect(self.logout)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Kelola Perawat"))
        self.pushButton_4.setText(_translate("MainWindow", " Kelola Pemeriksaan "))
        self.pushButton.setText(_translate("MainWindow", "Kelola Dokter"))
        self.pushButton_7.setText(_translate("MainWindow", "Kelola Admin"))
        self.pushButton_3.setText(_translate("MainWindow", "Kelola Pasien"))
        self.pushButton_6.setText(_translate("MainWindow", "Kelola Kasir"))
        self.label.setText(_translate("MainWindow", "Dashboard Admin"))
        self.pushButton_5.setText(_translate("MainWindow", "Logout"))
        
    def open_dokter(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kd.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()
        
    def open_perawat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kpr.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()
        
    def open_pasien(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kps.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show() 
        QtWidgets.QApplication.instance().activeWindow().close() 
        
    def open_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kpm.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()
        
    def open_admin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ka.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()
        
    def open_kasir(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()

    def logout(self):
        self.window = QtWidgets.QMainWindow()
        from form_login import Ui_MainWindow
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())