# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import kelola_dokter as kd
import kelola_perawat as kp
import kelola_pasien as kps
import kelola_pemeriksaan as kp
import kelola_admin as ka
import kelola_kasir as kk
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 140, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 140, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 250, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 360, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 250, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 360, 131, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.open_dokter)
        self.pushButton_2.clicked.connect(self.open_perawat)
        self.pushButton_3.clicked.connect(self.open_pasien)
        self.pushButton_4.clicked.connect(self.open_pemeriksaan)
        self.pushButton_6.clicked.connect(self.open_kasir)
        self.pushButton_7.clicked.connect(self.open_admin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dashboard Admin"))
        self.pushButton.setText(_translate("MainWindow", "Kelola Dokter"))
        self.pushButton_2.setText(_translate("MainWindow", "Kelola Perawat"))
        self.pushButton_3.setText(_translate("MainWindow", "Kelola Pasien"))
        self.pushButton_4.setText(_translate("MainWindow", " Kelola Pemeriksaan "))
        self.pushButton_6.setText(_translate("MainWindow", "Kelola Kasir"))
        self.pushButton_7.setText(_translate("MainWindow", "Kelola Admin"))
    
    def open_dokter(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kd.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_perawat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_pasien(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kps.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()  
        
    def open_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_admin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ka.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_kasir(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
