# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_insert_data_pemeriksaan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import kelola_pemeriksaan as kp
from pemeriksaan import Pemeriksaan
from subclass_dokter import Dokter
from subclass_perawat import Perawat
from subclass_pasien import Pasien
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 678)
        MainWindow.setStyleSheet("QMainWindow{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 651))
        self.frame.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(110, 430, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(360, 50, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(570, 250, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(110, 250, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 160, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(570, 160, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(110, 340, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(570, 340, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.dateEdit = QtWidgets.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(570, 370, 351, 41))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 190, 271, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 190, 61, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 370, 271, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 370, 61, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(570, 190, 271, 41))
        self.lineEdit_8.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(860, 190, 61, 41))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 280, 351, 41))
        self.label.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 460, 351, 41))
        self.label_2.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(570, 280, 351, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_4.clicked.connect(self.cari_dokter)
        self.pushButton_5.clicked.connect(self.cari_perawat)
        self.pushButton_8.clicked.connect(self.cari_pasien)
        self.pushButton_6.clicked.connect(self.insert_data)
        self.pushButton_7.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Nama Perawat"))
        self.label_4.setText(_translate("MainWindow", "Tambah Pemeriksaan"))
        self.label_11.setText(_translate("MainWindow", "Nama Pasien"))
        self.label_5.setText(_translate("MainWindow", "Nama Dokter"))
        self.label_6.setText(_translate("MainWindow", "ID Dokter"))
        self.label_21.setText(_translate("MainWindow", "ID Pasien"))
        self.label_16.setText(_translate("MainWindow", "ID Perawat"))
        self.label_17.setText(_translate("MainWindow", "Tanggal Pemeriksaan"))
        self.pushButton_7.setText(_translate("MainWindow", "Kembali"))
        self.pushButton_6.setText(_translate("MainWindow", "Simpan"))
        self.pushButton_4.setText(_translate("MainWindow", "Cari"))
        self.pushButton_5.setText(_translate("MainWindow", "Cari"))
        self.pushButton_8.setText(_translate("MainWindow", "Cari"))

    def cari_dokter(self):
        id_dokter = self.lineEdit_4.text()

        if not id_dokter:
            QtWidgets.QMessageBox.warning(None, "Error", "ID Dokter belum diisi")
            return

        data = Dokter.select_by_id(id_dokter)

        if data:
            self.label.setText(data[1])  # nama dokter
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Dokter tidak ditemukan")

    def cari_perawat(self):
        id_perawat = self.lineEdit_6.text()
        data = Perawat.select_by_id(id_perawat)

        if data:
            self.label_2.setText(data[1])
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Perawat tidak ditemukan")

    def cari_pasien(self):
        id_pasien = self.lineEdit_8.text()
        data = Pasien.select_by_id(id_pasien)

        if data:
            self.label_3.setText(data[1]) 
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Pasien tidak ditemukan")

    def insert_data(self):
        id_dokter = self.lineEdit_4.text().strip()
        id_perawat = self.lineEdit_6.text().strip()
        id_pasien = self.lineEdit_8.text().strip()

        tanggal = self.dateEdit.date().toString("yyyy-MM-dd")

        pemeriksaan = Pemeriksaan(
            id_dokter=id_dokter,
            id_perawat=id_perawat,
            id_pasien=id_pasien,
            tanggal=tanggal
        )
        pemeriksaan.insert()

        QtWidgets.QMessageBox.information(
            None,
            "Sukses",
            f"Data pemeriksaan berhasil ditambahkan\nID Pemeriksaan: {pemeriksaan.id}"
        )

        # reset form
        self.lineEdit_4.clear()
        self.lineEdit_6.clear()
        self.lineEdit_8.clear()
        self.label.clear()
        self.label_2.clear()
        self.label_3.clear()
        self.dateEdit.setDate(QtCore.QDate.currentDate())
    
    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kp.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())