# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_edit_data_pemeriksaan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import kelola_pemeriksaan as kp
from pemeriksaan import Pemeriksaan
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 330, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(300, 360, 181, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 300, 121, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 180, 121, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 300, 51, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 270, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 360, 81, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 430, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(300, 240, 121, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 270, 181, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 180, 51, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 300, 81, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 240, 51, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 240, 81, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 150, 121, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 430, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 330, 181, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 210, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 150, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 210, 151, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")

        # ================= READ ONLY FIELD =================
        readonly_style = """
        QLineEdit {
            background-color: #f0f0f0;
            color: #555;
        }
        """

        readonly_fields = [
            self.lineEdit_2,  # ID Dokter
            self.lineEdit_3,  # Nama Dokter
            self.lineEdit_5,  # ID Perawat
            self.lineEdit_4,  # Nama Perawat
            self.lineEdit_8,  # ID Pasien
            self.lineEdit_6   # Nama Pasien
        ]

        for field in readonly_fields:
            field.setReadOnly(True)
            field.setStyleSheet(readonly_style)
        
        # KONDISI AWAL
        self.lineEdit.setReadOnly(False)     # ID Pemeriksaan BISA DIKETIK
        self.lineEdit_7.setReadOnly(True)    # Tgl Pemeriksaan BELUM BISA

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 70, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 180, 81, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 150, 51, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_6.clicked.connect(self.cari_data)
        self.pushButton.clicked.connect(self.update_data)

        self.pushButton_2.clicked.connect(self.kembali)

        # tombol cari selain cari pemeriksaan tidak dipakai
        self.pushButton_3.hide()  # cari ID Dokter
        self.pushButton_4.hide()  # cari ID Perawat
        self.pushButton_5.hide()  # cari ID Pasien

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Nama Pasien"))
        self.pushButton_5.setText(_translate("MainWindow", "Cari"))
        self.label_6.setText(_translate("MainWindow", "Nama Perawat"))
        self.label_9.setText(_translate("MainWindow", "Tgl Pemeriksaan"))
        self.pushButton.setText(_translate("MainWindow", "Simpan"))
        self.pushButton_3.setText(_translate("MainWindow", "Cari"))
        self.label_7.setText(_translate("MainWindow", "ID Pasien"))
        self.pushButton_4.setText(_translate("MainWindow", "Cari"))
        self.label_5.setText(_translate("MainWindow", "ID Perawat"))
        self.pushButton_2.setText(_translate("MainWindow", "Kembali"))
        self.label_4.setText(_translate("MainWindow", "Nama Dokter"))
        self.label_2.setText(_translate("MainWindow", "ID Pemeriksaan"))
        self.label.setText(_translate("MainWindow", "Edit Pemeriksaan"))
        self.label_3.setText(_translate("MainWindow", "ID Dokter"))
        self.pushButton_6.setText(_translate("MainWindow", "Cari"))

    def cari_data(self):
        id_pem = self.lineEdit.text()

        if not id_pem:
            QtWidgets.QMessageBox.warning(
                None, "Error", "ID Pemeriksaan belum diisi"
            )
            return

        data = Pemeriksaan.select_detail_by_id(id_pem)

        if data:
            self.lineEdit.setText(str(data[0]))     # ID Pemeriksaan

            self.lineEdit_2.setText(str(data[1]))   # ID Dokter
            self.lineEdit_3.setText(data[2])        # Nama Dokter

            self.lineEdit_5.setText(str(data[3]))   # ID Perawat
            self.lineEdit_4.setText(data[4])        # Nama Perawat

            self.lineEdit_8.setText(str(data[5]))   # ID Pasien
            self.lineEdit_6.setText(data[6])        # Nama Pasien

            self.lineEdit_7.setText(str(data[7]))   # Tgl Pemeriksaan

            # 🔒 kunci ID Pemeriksaan
            self.lineEdit.setReadOnly(True)
            self.lineEdit.setStyleSheet("""
            QLineEdit {
                background-color: #f0f0f0;
                color: #555;
            }
            """)

            # ✏️ aktifkan edit tanggal
            self.lineEdit_7.setReadOnly(False)
            self.lineEdit_7.setStyleSheet("")

        else:
            QtWidgets.QMessageBox.warning(
                None, "Gagal", "Data pemeriksaan tidak ditemukan"
            )

    def update_data(self):
        id_pem = self.lineEdit.text()
        tanggal = self.lineEdit_7.text()

        if not id_pem or not tanggal:
            QtWidgets.QMessageBox.warning(None, "Error", "Data belum lengkap")
            return

        pemeriksaan = Pemeriksaan(id=id_pem, tanggal=tanggal)
        pemeriksaan.update_tanggal()

        QtWidgets.QMessageBox.information(
            None, "Sukses", "Tanggal pemeriksaan berhasil diperbarui"
        )

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kp.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
