# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_data_transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transaksi import Transaksi
from pemeriksaan import Pemeriksaan
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(400, 390, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 230, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 350, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 480, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 310, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 100, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(260, 350, 121, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 390, 131, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 480, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(400, 350, 111, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 100, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 430, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(150, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 140, 241, 31))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(260, 180, 241, 31))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 220, 241, 31))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(260, 260, 241, 31))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(260, 300, 241, 31))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(260, 420, 241, 31))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.cari_transaksi)
        self.pushButton_3.clicked.connect(self.hapus_transaksi)
        self.pushButton_4.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_4.setText(_translate("MainWindow", "Kontrol"))
        self.label_3.setText(_translate("MainWindow", "Nama Pasien"))
        self.label_7.setText(_translate("MainWindow", "Jenis Layanan"))
        self.label_5.setText(_translate("MainWindow", "Nama Perawat"))
        self.label.setText(_translate("MainWindow", "HAPUS TRANSAKSI"))
        self.label_4.setText(_translate("MainWindow", "Nama Dokter"))
        self.label_2.setText(_translate("MainWindow", "ID Pemeriksaan"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.label_6.setText(_translate("MainWindow", "Tgl Pemeriksaan"))
        self.checkBox.setText(_translate("MainWindow", "Pemeriksaan Umum"))
        self.checkBox_2.setText(_translate("MainWindow", "Pemeriksaan Spesialis"))
        self.pushButton_3.setText(_translate("MainWindow", "Hapus"))
        self.checkBox_3.setText(_translate("MainWindow", "Konsultasi Dokter"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))
        self.label_8.setText(_translate("MainWindow", "Total Bayar"))
        self.label_9.setText(_translate("MainWindow", "Penyakit"))

    def cari_transaksi(self):
        id_pemeriksaan = self.lineEdit.text()

        if id_pemeriksaan == "":
            QtWidgets.QMessageBox.warning(None, "Error", "ID Pemeriksaan wajib diisi")
            return

        transaksi = Transaksi()
        data = transaksi.cari_by_pemeriksaan(id_pemeriksaan)

        if not data:
            QtWidgets.QMessageBox.warning(None, "Error", "Transaksi tidak ditemukan")
            return

        (
            nama_dokter,
            nama_perawat,
            nama_pasien,
            penyakit,
            tgl_pemeriksaan,
            total_bayar,
            layanan_list
        ) = data

        self.label_10.setText(nama_dokter)
        self.label_11.setText(nama_perawat)
        self.label_12.setText(nama_pasien)
        self.label_13.setText(penyakit)
        self.label_14.setText(tgl_pemeriksaan.strftime("%d-%m-%Y"))
        self.label_15.setText(self.format_rupiah(total_bayar))

        # reset checkbox dulu
        for cb in [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]:
            cb.setChecked(False)

        # centang sesuai layanan
        for layanan in layanan_list:
            if layanan == "Pemeriksaan Umum":
                self.checkBox.setChecked(True)
            elif layanan == "Pemeriksaan Spesialis":
                self.checkBox_2.setChecked(True)
            elif layanan == "Konsultasi Dokter":
                self.checkBox_3.setChecked(True)
            elif layanan == "Kontrol":
                self.checkBox_4.setChecked(True)

    def format_rupiah(self, angka):
        return "Rp {:,}".format(angka).replace(",", ".")

    def hapus_transaksi(self):
        id_pemeriksaan = self.lineEdit.text()

        if id_pemeriksaan == "":
            QtWidgets.QMessageBox.warning(None, "Error", "ID Pemeriksaan wajib diisi")
            return

        reply = QtWidgets.QMessageBox.question(
            None,
            "Konfirmasi",
            "Yakin ingin menghapus transaksi ini?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            transaksi = Transaksi()
            transaksi.delete_by_pemeriksaan(id_pemeriksaan)

            QtWidgets.QMessageBox.information(
                None, "Success", "Transaksi berhasil dihapus"
            )

            self.clear_form()

    def clear_form(self):
        self.lineEdit.clear()
        self.label_10.clear()
        self.label_11.clear()
        self.label_12.clear()
        self.label_13.clear()
        self.label_14.clear()
        self.label_15.clear()

        for cb in [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]:
            cb.setChecked(False)

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
