# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_pasien.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import kelola_pasien as kp
from subclass_pasien import Pasien
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 682)
        MainWindow.setStyleSheet("QMainWindow{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.frame_2.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(200, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 180, 61, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(130, 420, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(130, 360, 351, 41))
        self.label_18.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(130, 450, 351, 41))
        self.label_19.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 180, 271, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(130, 240, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(130, 150, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(130, 270, 351, 41))
        self.label_22.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(130, 330, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_5.clicked.connect(self.cari_data)
        self.pushButton_7.clicked.connect(self.hapus_data)
        self.pushButton_6.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Hapus Pasien"))
        self.pushButton_5.setText(_translate("MainWindow", "Cari"))
        self.label_17.setText(_translate("MainWindow", "Sakit"))
        self.label_20.setText(_translate("MainWindow", "Nama"))
        self.pushButton_6.setText(_translate("MainWindow", "Kembali"))
        self.label_21.setText(_translate("MainWindow", "ID"))
        self.pushButton_7.setText(_translate("MainWindow", "Hapus"))
        self.label_23.setText(_translate("MainWindow", "Umur"))

    def cari_data(self):
        id_pasien = self.lineEdit_4.text()
        data = Pasien.select_by_id(id_pasien)

        if data:
            self.label_22.setText(data[1])       
            self.label_18.setText(str(data[2]))    
            self.label_19.setText(data[3])          

    def hapus_data(self):
        id_pasien = self.lineEdit_4.text()

        pasien = Pasien(id=id_pasien,nama="",umur=0,penyakit="")
        pasien.delete()

        self.lineEdit_4.clear()
        self.label_22.clear()
        self.label_18.clear()
        self.label_19.clear()

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kp.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())