# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_delete_data_transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transaksi import Transaksi
from pemeriksaan import Pemeriksaan
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 678)
        MainWindow.setStyleSheet("QMainWindow{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 651))
        self.frame.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(570, 140, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(410, 40, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 170, 61, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(570, 320, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(570, 260, 351, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(110, 320, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 170, 271, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 230, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 560, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 140, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(110, 260, 351, 41))
        self.label_12.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(110, 350, 351, 41))
        self.label_13.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(550, 560, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(570, 424, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(570, 170, 351, 41))
        self.label_15.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(570, 260, 351, 41))
        self.label_31.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(110, 410, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(570, 230, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(570, 454, 351, 41))
        self.label_34.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(110, 440, 351, 41))
        self.label_35.setStyleSheet("QLabel {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(580, 350, 171, 23))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(580, 380, 181, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(780, 350, 151, 23))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(780, 380, 95, 23))
        self.checkBox_4.setObjectName("checkBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_3.clicked.connect(self.cari_transaksi)
        self.pushButton_7.clicked.connect(self.hapus_transaksi)
        self.pushButton_4.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Penyakit"))
        self.label_4.setText(_translate("MainWindow", "Hapus Transaksi"))
        self.pushButton_3.setText(_translate("MainWindow", "Cari"))
        self.label_11.setText(_translate("MainWindow", "Jenis Layanan"))
        self.label_5.setText(_translate("MainWindow", "Nama Perawat"))
        self.label_6.setText(_translate("MainWindow", "Nama Dokter"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.label_10.setText(_translate("MainWindow", "ID Transaksi"))
        self.pushButton_7.setText(_translate("MainWindow", "Hapus"))
        self.label_14.setText(_translate("MainWindow", "Total Bayar"))
        self.label_32.setText(_translate("MainWindow", "Nama Pasien"))
        self.label_33.setText(_translate("MainWindow", "Tanggal Pemeriksaan"))
        self.checkBox.setText(_translate("MainWindow", "Pemeriksaan Umum"))
        self.checkBox_2.setText(_translate("MainWindow", "Pemeriksaan Spesialis"))
        self.checkBox_3.setText(_translate("MainWindow", "Konsultasi Dokter"))
        self.checkBox_4.setText(_translate("MainWindow", "Kontrol"))

    def cari_transaksi(self):
        id_transaksi = self.lineEdit_4.text()

        if id_transaksi == "":
            QtWidgets.QMessageBox.warning(None, "Error", "ID Pemeriksaan wajib diisi")
            return

        transaksi = Transaksi()
        data = transaksi.cari_by_pemeriksaan(id_transaksi)

        if not data:
            QtWidgets.QMessageBox.warning(None, "Error", "Transaksi tidak ditemukan")
            return

        (
            nama_dokter,
            nama_perawat,
            nama_pasien,
            penyakit,
            tgl_pemeriksaan,
            total_bayar,
            layanan_list
        ) = data

        self.label_12.setText(nama_dokter)
        self.label_13.setText(nama_perawat)
        self.label_35.setText(nama_pasien)
        self.label_15.setText(penyakit)
        self.label_31.setText(tgl_pemeriksaan.strftime("%d-%m-%Y"))
        self.label_34.setText(self.format_rupiah(total_bayar))

        # reset checkbox dulu
        for cb in [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]:
            cb.setChecked(False)

        # centang sesuai layanan
        for layanan in layanan_list:
            if layanan == "Pemeriksaan Umum":
                self.checkBox.setChecked(True)
            elif layanan == "Pemeriksaan Spesialis":
                self.checkBox_2.setChecked(True)
            elif layanan == "Konsultasi Dokter":
                self.checkBox_3.setChecked(True)
            elif layanan == "Kontrol":
                self.checkBox_4.setChecked(True)

    def format_rupiah(self, angka):
        return "Rp {:,}".format(angka).replace(",", ".")

    def hapus_transaksi(self):
        id_transaksi = self.lineEdit_4.text()

        if id_transaksi == "":
            QtWidgets.QMessageBox.warning(None, "Error", "ID Pemeriksaan wajib diisi")
            return

        reply = QtWidgets.QMessageBox.question(
            None,
            "Konfirmasi",
            "Yakin ingin menghapus transaksi ini?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            transaksi = Transaksi()
            transaksi.delete_by_id(id_transaksi)

            QtWidgets.QMessageBox.information(
                None, "Success", "Transaksi berhasil dihapus"
            )

            self.clear_form()

    def clear_form(self):
        self.lineEdit_4.clear()
        self.label_12.clear()
        self.label_13.clear()
        self.label_35.clear()
        self.label_15.clear()
        self.label_31.clear()
        self.label_34.clear()

        for cb in [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]:
            cb.setChecked(False)

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())