# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_insert_data_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import kelola_admin as ka
from level import Level
from subclass_admin import Admin
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 676)
        MainWindow.setStyleSheet("QMainWindow{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 651))
        self.frame.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(570, 180, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(400, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(570, 360, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(110, 360, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 210, 351, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 270, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 180, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(570, 270, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(570, 270, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 300, 351, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 390, 351, 41))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(570, 210, 351, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(570, 300, 351, 41))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(570, 390, 351, 41))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 510, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 510, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_6.clicked.connect(self.insert_data)
        self.pushButton_7.clicked.connect(self.kembali)
        self.getDataLevel()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Tambah Admin"))
        self.label_11.setText(_translate("MainWindow", "Level"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.label_6.setText(_translate("MainWindow", "Nama"))
        self.label_10.setText(_translate("MainWindow", "ID"))
        self.label_14.setText(_translate("MainWindow", "Umur"))
        self.label_21.setText(_translate("MainWindow", "Umur"))
        self.pushButton_7.setText(_translate("MainWindow", "Kembali"))
        self.pushButton_6.setText(_translate("MainWindow", "Simpan"))

    def getDataLevel(self):
        data = Level.get_admin_kasir_levels() 

        for id_level, nama_level in data:
            self.comboBox.addItem(nama_level, id_level)
    
    def insert_data(self):
        id_admin = self.lineEdit_3.text()
        nama = self.lineEdit_4.text()
        username = self.lineEdit_5.text()
        password = self.lineEdit_6.text()
        umur = self.lineEdit_7.text()
        level = self.comboBox.currentData()

        admin = Admin(id=id_admin,nama=nama,umur=umur,id_level=level,username=username,password=password)
        admin.insert()


    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ka.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())