# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_insert_data_dokter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import kelola_dokter as kd
from subclass_dokter import Dokter
from level import Level
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 672)
        MainWindow.setStyleSheet("QMainWindow{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.frame_2.setStyleSheet("QFrame{ \n"
"    background-color: rgb(255, 249, 239);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(200, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(130, 420, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 180, 351, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(130, 240, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(130, 150, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(130, 330, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 270, 351, 41))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 360, 351, 41))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(130, 460, 351, 41))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 2px solid rgb(76, 115, 255);\n"
"    background-color: rgb(219, 224, 255);\n"
"    border-radius: 8px\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 550, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_6.clicked.connect(self.insert_data)
        self.pushButton_7.clicked.connect(self.kembali)
        self.getDataSpesialis()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Tambah Dokter"))
        self.label_17.setText(_translate("MainWindow", "Level"))
        self.label_20.setText(_translate("MainWindow", "Nama"))
        self.label_21.setText(_translate("MainWindow", "ID"))
        self.label_23.setText(_translate("MainWindow", "Umur"))
        self.pushButton_7.setText(_translate("MainWindow", "Kembali"))
        self.pushButton_6.setText(_translate("MainWindow", "Simpan"))

    def insert_data(self):
        id_dokter = self.lineEdit_4.text()
        nama = self.lineEdit_5.text()
        umur = int(self.lineEdit_6.text())

        id_level = self.comboBox.currentData()  
        spesialis = self.comboBox.currentText()

        dokter = Dokter(id=id_dokter,nama=nama,umur=umur,id_level=id_level, spesialis=spesialis)
        dokter.insert()

    def getDataSpesialis(self):
        self.comboBox.clear()
        self.comboBox.addItem("-- Pilih Level --", None)

        data_level = Level.get_level_dokter()

        for id_level, nama_level in data_level:
            self.comboBox.addItem(nama_level, id_level)

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = kd.Ui_MainWindow() 
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())