# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_insert_data_transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transaksi import Transaksi
from pemeriksaan import Pemeriksaan
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 150, 171, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 200, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 240, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 320, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 360, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 440, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 190, 241, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 230, 241, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 270, 241, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 310, 241, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(250, 430, 241, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 150, 61, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 490, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(230, 490, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(250, 360, 121, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(250, 400, 131, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(390, 360, 111, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(390, 400, 70, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.cari_pemeriksaan)
        self.pushButton_3.clicked.connect(self.simpan_transaksi)
        self.pushButton_4.clicked.connect(self.kembali)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TAMBAH TRANSAKSI"))
        self.label_2.setText(_translate("MainWindow", "ID Pemeriksaan"))
        self.label_3.setText(_translate("MainWindow", "Nama Pasien"))
        self.label_4.setText(_translate("MainWindow", "Nama Dokter"))
        self.label_5.setText(_translate("MainWindow", "Nama Perawat"))
        self.label_6.setText(_translate("MainWindow", "Tgl Pemeriksaan"))
        self.label_7.setText(_translate("MainWindow", "Jenis Layanan"))
        self.label_8.setText(_translate("MainWindow", "Total Bayar"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))
        self.pushButton_3.setText(_translate("MainWindow", "Simpan"))
        self.pushButton_4.setText(_translate("MainWindow", "Kembali"))
        self.checkBox.setText(_translate("MainWindow", "Pemeriksaan Umum"))
        self.checkBox_2.setText(_translate("MainWindow", "Pemeriksaan Spesialis"))
        self.checkBox_3.setText(_translate("MainWindow", "Konsultasi Dokter"))
        self.checkBox_4.setText(_translate("MainWindow", "Kontrol"))

    def cari_pemeriksaan(self):
        id_pemeriksaan = self.lineEdit.text()
        pemeriksaan = Pemeriksaan()
        data = pemeriksaan.cari_data(id_pemeriksaan)

        if data:
            self.lineEdit_2.setText(data[1])  # nama dokter
            self.lineEdit_3.setText(data[2])  # nama perawat
            self.lineEdit_4.setText(data[3])  # nama pasien
            self.lineEdit_6.setText(data[4].strftime("%d-%m-%Y"))
        else:
            QtWidgets.QMessageBox.warning(
                None, "Error", "Data pemeriksaan tidak ditemukan."
            )

    def hitung_total_bayar(self):
        total = 0

        if self.checkBox.isChecked():      # Pemeriksaan Umum
            total += 50000

        if self.checkBox_2.isChecked():    # Pemeriksaan Spesialis
            total += 100000

        if self.checkBox_3.isChecked():    # Konsultasi Dokter
            total += 30000

        if self.checkBox_4.isChecked():    # Kontrol
            total += 20000

        self.lineEdit_7.setText(str(total))
        return total

    def simpan_transaksi(self):
        id_pemeriksaan = self.lineEdit.text()

        if id_pemeriksaan == "":
            QtWidgets.QMessageBox.warning(None, "Error", "ID Pemeriksaan wajib diisi")
            return

        total_bayar = self.hitung_total_bayar()

        if total_bayar == 0:
            QtWidgets.QMessageBox.warning(
                None, "Error", "Pilih minimal satu layanan"
            )
            return

        transaksi = Transaksi(
            id_pemeriksaan=id_pemeriksaan,
            tanggal=QtCore.QDate.currentDate().toPyDate(),
            total_bayar=total_bayar
        )

        id_transaksi = transaksi.insert()  # pastikan insert return id_transaksi

        # ================= DETAIL TRANSAKSI =================
        from detail_transaksi import DetailTransaksi

        if self.checkBox.isChecked():
            DetailTransaksi(id_transaksi, 1).insert()

        if self.checkBox_2.isChecked():
            DetailTransaksi(id_transaksi, 2).insert()

        if self.checkBox_3.isChecked():
            DetailTransaksi(id_transaksi, 3).insert()

        if self.checkBox_4.isChecked():
            DetailTransaksi(id_transaksi, 4).insert()

        QtWidgets.QMessageBox.information(
            None, "Success", "Transaksi berhasil disimpan"
        )

    def kembali(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.close()

        QtWidgets.QApplication.instance().activeWindow().close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
