# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kelola_pemeriksaan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import form_insert_data_pemeriksaan as fidp
import form_edit_data_pemeriksaan as fedp
import form_delete_data_pemeriksaan as fddp
import lihat_data_pemeriksaan as ldp
import dashboard_admin as da
import kelola_admin as ka
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 688)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 661))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 210, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(270, 210, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 410, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(620, 410, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 115, 1);\n"
"   color: white;    \n"
"   border-radius: 15px;   \n"
"   padding: 6px;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1131, 111))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 0, 255);\n"
"    border-radius: 5px        \n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(440, 30, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color : white\n"
"    }")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(1010, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 0, 0);\n"
"   color: white;    \n"
"   border-radius: 5px;   \n"
"   padding: 6px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.open_tambah_pemeriksaan)
        self.pushButton_2.clicked.connect(self.open_edit_pemeriksaan)
        self.pushButton_3.clicked.connect(self.open_hapus_pemeriksaan)
        self.pushButton_6.clicked.connect(self.open_lihat_pemeriksaan)
        self.pushButton_5.clicked.connect(self.keluar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Update Data"))
        self.pushButton.setText(_translate("MainWindow", "Tambah Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Hapus Data"))
        self.pushButton_6.setText(_translate("MainWindow", "Lihat Data"))
        self.label.setText(_translate("MainWindow", "Kelola Pemeriksaan"))
        self.pushButton_5.setText(_translate("MainWindow", "Keluar"))

    def open_tambah_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = fidp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

    def open_edit_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = fedp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

    def open_hapus_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = fddp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

    def open_lihat_pemeriksaan(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = ldp.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

    def keluar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())