# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_data_pemeriksaan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pemeriksaan import Pemeriksaan
import kelola_pemeriksaan as kpr
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 679)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 651))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(940, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 911, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("padding: 6px;\n"
"background: white;\n"
"border: 2px solid #ccc;\n"
"border-radius: 8px;\n"
"font-size: 14px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Cari ID")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 210, 991, 401))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background: white;\n"
"    border: 1px solid #aaa;\n"
"    gridline-color: #777;\n"
"    font-size: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #eaeaea;\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1031, 111))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 0, 255);\n"
"    border-radius: 5px        \n"
"}")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(390, 30, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color : white\n"
"    }")
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(920, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 0, 0);\n"
"   color: white;    \n"
"   border-radius: 5px;   \n"
"   padding: 6px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.cari_pemeriksaan)
        self.pushButton_5.clicked.connect(self.kembali)

        self.tampil_semua_pemeriksaan()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))
        self.tableWidget.setSortingEnabled(True)
        self.label_3.setText(_translate("MainWindow", "Data Pemeriksaan"))
        self.pushButton_5.setText(_translate("MainWindow", "Kembali"))

    def load_data(self, data):
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)

        self.tableWidget.setHorizontalHeaderLabels([
            "ID Pemeriksaan",
            "ID Dokter",
            "ID Perawat",
            "ID Pasien",
            "Tgl Pemeriksaan"
        ])

        # tabel hanya view (tidak bisa diedit)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )

        # kolom otomatis menyesuaikan lebar
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        for row_number, row_data in enumerate(data):
            self.tableWidget.insertRow(row_number)

            for column_number, item in enumerate(row_data):
                cell = QtWidgets.QTableWidgetItem(str(item))

                # rata tengah untuk kolom ID
                if column_number in (0, 1, 2, 3):
                    cell.setTextAlignment(QtCore.Qt.AlignCenter)

                self.tableWidget.setItem(
                    row_number,
                    column_number,
                    cell
                )

    def cari_pemeriksaan(self):
        id_pemeriksaan = self.lineEdit.text()

        if id_pemeriksaan:
            data = Pemeriksaan.get_by_id(id_pemeriksaan)
        else:
            data = Pemeriksaan.get_all()

        if data:
            self.load_data(data)
        else:
            QtWidgets.QMessageBox.information(
                None, "Info", "Data pemeriksaan tidak ditemukan"
            )

    def tampil_semua_pemeriksaan(self):
        data = Pemeriksaan.get_all()
        self.load_data(data)

    def kembali(self):      
        self.window = QtWidgets.QMainWindow()
        self.ui = kpr.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())