# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_riwayat_transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transaksi import Transaksi
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: white;\n"
"    border-radius: 5px;   \n"
"    padding: 6px;           \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("padding: 6px;\n"
"background: white;\n"
"border: 2px solid #ccc;\n"
"border-radius: 8px;\n"
"font-size: 14px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 90, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 190, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(110, 240, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background: white;\n"
"    border: 1px solid #aaa;\n"
"    gridline-color: #777;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #eaeaea;\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderLabels([
        "ID Transaksi",
        "ID Pemeriksaan",
        "Nama Pasien",
        "Penyakit",
        "Tanggal",
        "Total Bayar"
        ])
        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        self.pushButton.clicked.connect(self.load_semua)
        self.pushButton_2.clicked.connect(self.cari_transaksi)
        self.pushButton_2.clicked.connect(self.kembali)
        self.load_semua()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Kembali"))
        self.label.setText(_translate("MainWindow", "Riwayat Transaksi"))
        self.label_2.setText(_translate("MainWindow", "ID Transaksi"))
        self.tableWidget.setSortingEnabled(True)
        self.pushButton.setText(_translate("MainWindow", "Cari"))

    def tampilkan_data(self, data):
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(data):
            self.tableWidget.insertRow(row_number)

            for column_number, value in enumerate(row_data):

                # format tanggal
                if hasattr(value, "strftime"):
                    value = value.strftime("%d-%m-%Y")

                self.tableWidget.setItem(
                    row_number,
                    column_number,
                    QtWidgets.QTableWidgetItem(str(value))
                )

    def load_semua(self):
        data = Transaksi.riwayat()
        self.tampilkan_data(data)

    def kembali(self):      
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
