# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_riwayat_transaksi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from transaksi import Transaksi
import dashboard_kasir as dk
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 676)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 651))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 243, 229);          \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(940, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 8px;\n"
"    color: white\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 911, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("padding: 6px;\n"
"background: white;\n"
"border: 2px solid #ccc;\n"
"border-radius: 8px;\n"
"font-size: 14px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("Cari ID")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 210, 991, 401))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background: white;\n"
"    border: 1px solid #aaa;\n"
"    gridline-color: #777;\n"
"    font-size: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #eaeaea;\n"
"    font-weight: bold;\n"
"    padding: 6px;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1031, 111))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 0, 255);\n"
"    border-radius: 5px        \n"
"}")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(420, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color : white\n"
"    }")
        self.label_3.setObjectName("label_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(920, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(255, 0, 0);\n"
"   color: white;    \n"
"   border-radius: 5px;   \n"
"   padding: 6px;}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.cari_transaksi)
        self.pushButton_5.clicked.connect(self.kembali)
        self.load_semua()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Cari"))
        self.tableWidget.setSortingEnabled(True)
        self.label_3.setText(_translate("MainWindow", "Data Transaksi"))
        self.pushButton_5.setText(_translate("MainWindow", "Kembali"))

    def tampilkan_data(self, data):
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)

        self.tableWidget.setHorizontalHeaderLabels([
            "ID Transaksi",
            "ID Pemeriksaan",
            "Nama Pasien",
            "Penyakit",
            "Tanggal",
            "Total Bayar"
        ])

        # tabel hanya view (tidak bisa diedit)
        self.tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )

        # kolom otomatis menyesuaikan lebar
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        for row_number, row_data in enumerate(data):
            self.tableWidget.insertRow(row_number)

            for column_number, value in enumerate(row_data):

                # format tanggal
                if hasattr(value, "strftime"):
                    value = value.strftime("%d-%m-%Y")

                # format rupiah (kolom Total Bayar)
                if column_number == 5:
                    value = self.format_rupiah(value)

                cell = QtWidgets.QTableWidgetItem(str(value))

                # rata tengah untuk ID & Tanggal
                if column_number in (0, 1, 4):
                    cell.setTextAlignment(QtCore.Qt.AlignCenter)

                # rata kanan untuk Total Bayar
                if column_number == 5:
                    cell.setTextAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)

                self.tableWidget.setItem(
                    row_number,
                    column_number,
                    cell
                )

    def format_rupiah(self, angka):
        try:
            return "Rp {:,}".format(int(angka)).replace(",", ".")
        except:
            return "Rp 0"

    def cari_transaksi(self):
        id_transaksi = self.lineEdit.text().strip()

        # kalau kosong, tampilkan semua
        if not id_transaksi:
            self.load_semua()
            return

        data = Transaksi.riwayat(id_transaksi)

        if not data:
            QtWidgets.QMessageBox.information(
                None,
                "Info",
                "Data transaksi tidak ditemukan"
            )
            self.tableWidget.setRowCount(0)
            return

        self.tampilkan_data(data)

    def load_semua(self):
        data = Transaksi.riwayat()
        self.tampilkan_data(data)

    def kembali(self):      
        self.window = QtWidgets.QMainWindow()
        self.ui = dk.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

        QtWidgets.QApplication.instance().activeWindow().close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())